version: '3.8'

services:
###> doctrine/doctrine-bundle ###
    mysql:
        image: mysql:8.0
        platform: linux/x86_64
        container_name: app-mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DB:-app}
            MYSQL_USER: ${MYSQL_USER:-symfony}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
        ports:
            - '53306:3306'
        volumes: 
            - ./docker/db/mysql:/var/lib/mysql:rw,cached
###< doctrine/doctrine-bundle ###
    php:
        platform: linux/x86_64
        container_name: app-php
        environment:
            - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL:-mysql://symfony:ChangeMe@mysql:3306/app?serverVersion=8.0&charset=utf8mb4}
        build:
            context: .
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                SKELETON: ${SKELETON:-symfony/skeleton}
                STABILITY: ${STABILITY:-stable}
                DEVELOPER_EMAIL: ${DEVELOPER_EMAIL:-developer@domain.com}
                DEVELOPER_USER: ${DEVELOPER_EMAIL:-developer}
            target: php
        ports:
            - '59000:9000'
        volumes:
            - ./:/srv/app:rw,cached
        depends_on:
            - mysql

    nginx:
        image: nginx:stable-alpine
        platform: linux/x86_64
        container_name: app-nginx
        ports:
            - '5580:80'
            - '5443:443'
        volumes:
            - ./public:/srv/app/public
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/ssl/localhost.key:/etc/ssl/localhost.key
            - ./docker/nginx/ssl/localhost.crt:/etc/ssl/localhost.crt
        depends_on:
            - php
            - mysql
